# Generated by Django 4.1.13 on 2024-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_icon_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
    ]
