# Generated by Django 4.1.13 on 2024-03-26 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='etudiant',
            new_name='apprenant',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='contenu_commentaire',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='enseignant',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='courseprogressscore',
            old_name='Apprenant',
            new_name='apprenant',
        ),
        migrations.RenameField(
            model_name='courseprogressscore',
            old_name='score',
            new_name='progression',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='etudiant',
            new_name='apprenant',
        ),
        migrations.RemoveField(
            model_name='category',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='contenu_audio',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='contenu_image',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='contenu_texte',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='contenu_video',
        ),
        migrations.AddField(
            model_name='category',
            name='desciption_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lecon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lecon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.module'),
        ),
        migrations.CreateModel(
            name='contenuVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('video', models.URLField(blank=True, null=True)),
                ('desciption_video', models.CharField(default='', max_length=255)),
                ('ordre', models.IntegerField(default=0)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='contenuTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='contenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu_image', models.ImageField(blank=True, null=True, upload_to='assets/lecons/images')),
                ('desciption_image', models.CharField(default='', max_length=255)),
                ('ordre', models.IntegerField(default=0)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='contenuAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='assets/lecons/audio')),
                ('desciption_audio', models.CharField(default='', max_length=255)),
                ('ordre', models.IntegerField(default=0)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecon')),
            ],
        ),
    ]
