# Generated by Django 4.1.13 on 2024-03-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_etudiant_commentaire_apprenant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='author',
            new_name='auteur',
        ),
    ]
