# Generated by Django 4.1.13 on 2024-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_author_cours_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='dernier_ordre',
            field=models.IntegerField(default=0),
        ),
    ]
