# Generated by Django 4.1.13 on 2024-03-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_cours_ratings_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='module',
        ),
        migrations.AddField(
            model_name='lecon',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.cours'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
