# Generated by Django 4.1.13 on 2024-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_lecon_module_lecon_cours_delete_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenuvideo',
            old_name='video',
            new_name='lien_video',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='apprenant',
        ),
        migrations.RemoveField(
            model_name='contenuaudio',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='contenuimage',
            name='contenu_image',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='ratings',
        ),
        migrations.AddField(
            model_name='contenuaudio',
            name='lien_audio',
            field=models.FileField(blank=True, null=True, upload_to='media/assets/lecons/audio'),
        ),
        migrations.AddField(
            model_name='contenuimage',
            name='lien_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/assets/lecons/images'),
        ),
        migrations.AddField(
            model_name='cours',
            name='langue',
            field=models.CharField(choices=[('français', 'Français'), ('anglais', 'Anglais'), ('espagnol', 'Espagnol'), ('allemand', 'Allemand'), ('italien', 'Italien'), ('portugais', 'Portugais'), ('chinois', 'Chinois'), ('arabe', 'Arabe')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='progression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/assets/category/autre.PNG', upload_to='media/assets/category'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cours_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/assets/cours'),
        ),
        migrations.DeleteModel(
            name='CourseProgressScore',
        ),
    ]
