# Generated by Django 4.1.13 on 2024-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_video_contenuvideo_lien_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='assets/category/autre.PNG', upload_to='assets/category'),
        ),
        migrations.AlterField(
            model_name='contenuaudio',
            name='lien_audio',
            field=models.FileField(blank=True, null=True, upload_to='assets/lecons/audio'),
        ),
        migrations.AlterField(
            model_name='contenuimage',
            name='lien_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/lecons/images'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cours_photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
