# Generated by Django 4.1.13 on 2024-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='apprenant',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/assets/quiz'),
        ),
    ]
