# Generated by Django 4.1.13 on 2024-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_apprenant_alter_quiz_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/quiz'),
        ),
    ]
