# Generated by Django 4.1.13 on 2024-04-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='discussion',
            new_name='question_poser',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='auteur',
        ),
    ]
