# Generated by Django 4.1.13 on 2024-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('apprenant', 'Apprenant'), ('auteur', 'Auteur')], max_length=20),
        ),
    ]
