# Generated by Django 4.1.13 on 2024-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_onetimepassword_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cin',
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville'),
        ),
    ]
